server.port=8080
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST
spring.web.cors.allowed-headers=*

#email stuff
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=louisklein71@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.recaptcha.secret=${RECAPTCHA_SECRET}