export const ENEMY_TYPES = {
  imp: {
    frameWidth: 16,
    frameHeight: 16,
    frameCount: 4,
    animSpeed: 800,
    speed: 1,
    hp: 5,
    damage: 1,
    sprite: "imp",
    z: 10,
    offsetAdjust: { x: -22, y: 0 },
  },
  elite: {
    frameWidth: 32,
    frameHeight: 32,
    frameCount: 4,
    animSpeed: 1400,
    speed: 0.5,
    hp: 20,
    damage: 5,
    sprite: "elite",
    z: 10,
    offsetAdjust: { x: -14, y: 0 },
  },
  fast: {
    frameWidth: 24,
    frameHeight: 16,
    frameCount: 4,
    animSpeed: 350,
    speed: 2.25,
    hp: 5,
    damage: 3,
    sprite: "fast",
    z: 9,
    offsetAdjust: { x: -16, y: -10 },
  },
  splitter: {
    frameWidth: 24,
    frameHeight: 32,
    frameCount: 4,
    animSpeed: 600,
    speed: 0.8,
    hp: 5,
    damage: 6,
    sprite: "splitter",
    z: 10,
    offsetAdjust: { x: -16, y: 0 },
  },
  flyer: {
    frameWidth: 32,
    frameHeight: 24,
    frameCount: 4,
    animSpeed: 200,
    speed: 1,
    hp: 10,
    damage: 5,
    sprite: "flyer",
    z: 1000,
    offsetAdjust: { x: -16, y: 0 },
  },
  boss: {
    frameWidth: 32,
    frameHeight: 32,
    frameCount: 4,
    animSpeed: 800,
    speed: .6,
    hp: 20,
    maxHp: 20,
    damage: 50,
    sprite: "boss",
    z: 10,
    offsetAdjust: { x: -16, y: 0 },
  },
};
