export const TOWER_TYPES = {
  wall: {
    sprite: "wall",
    buildable: true,
    range: 0,
    damage: 0,
    pierce: 0,
    aoe: 0,
    bounce: 0,
    fireRate: 0,
    bulletSpeed: 1,
  },
  arrow: {
    sprite: "arrow",
    range: 220,
    damage: 1,
    pierce: 2,
    aoe: 0,
    bounce: 0,
    fireRate: 800,
    buildable: true,
    bulletSpeed: 6,
    bulletSprite: "bullet"
  },
  cannon: {
    sprite: "cannon",
    range: 160,
    damage: 1,
    pierce: 0,
    aoe: 1,
    bounce: 0,
    fireRate: 1200,
    buildable: true,
    bulletSpeed: 5,
    bulletSprite: "cannonball"
  },
    slow: {
    sprite: "slow",
    range: 160,
    damage: 0,
    pierce: 0,
    aoe: 1,    
    bounce: 0,
    fireRate: 1200,
    buildable: true,
    bulletSpeed: 5,
    bulletSprite: "cannonball"
  },
    acid: {
    sprite: "acid",
    range: 100,
    damage: 1,
    pierce: 1000,
    aoe: 0,    
    bounce: 0,
    fireRate: 600,
    buildable: true,
    bulletSpeed: 10,
    bulletSprite: "splash"
  },
  chain: {
    sprite: "chain",
    range: 160,
    damage: 1,
    pierce: 0,
    aoe: 0,
    bounce: 2,
    fireRate: 1200,
    buildable: true,
    bulletSpeed: 100,
    bulletSprite: "lightning"
  },
  sniper: {
    sprite: "sniper",
    range: 100000,
    damage: 1,
    pierce: 0,
    aoe: 0,
    bounce: 0,
    fireRate: 1200,
    buildable: true,
    bulletSpeed: Infinity,
    bulletSprite: "bullet"
  },
  buff: {
    sprite: "buff",
    range: 220,
    damage: 0,
    pierce: 0,
    aoe: 0,
    bounce: 0,
    fireRate: 1000,
    buildable: true,
    bulletSpeed: Infinity,
  },
};